### ISSUE TITLE
Add a nyancat reporter

### ISSUE THREAD

**Issue by biohazard999** [xenial-io/Tasty#39]
Cause every good test framework needs more cat's we should add an nyancat-reporter.

This also would showcase and harden the API surface for reporters as well as custom and user made plugins.

See [jest-nyancat-reporter](https://github.com/philihp/jest-nyancat-reporter) as an inspriation.

**Comment by hazard999** [comment]
Here is the correct link:

[https://github.com/philihp/jest-nyancat-reporter](url)

**Comment by biohazard999** [comment]
This also leads to the question if we only should allow one set of console reporters at a time and make them an API thing. Currently you can register multiple reporters, which is a good idea I think (think of binary and file based reporters) but there is no good story for console based reporters yet, cause they will conflict by pure nature.
