### ISSUE TITLE
README.md: Add contribution instructions to include Terminal.Gui

### ISSUE THREAD

**Issue by Paramethod** [xenial-io/Tasty#71]
Xenial.Tasty.sln references Terminal.Gui in "ext\gui.cs\Terminal.Gui\Terminal.Gui.csproj" which isn't included. 

I'm guessing this is the missing project -> https://github.com/migueldeicaza/gui.cs but it doesn't seem to be same version. I also tried to use your forked version -> https://github.com/biohazard999/gui.cs but this one is also not up-to-date. `Terminal.Gui.View.SetFocus` doesn't have an overload with 1 argument.

**Comment by biohazard999** [comment]
That should be covered by the git submodule commands. Did you had any troubles?

**Comment by biohazard999** [comment]
https://github.com/xenial-io/Tasty#building

This is a temp fix until terminal.gui provides a new nuget

**Comment by Paramethod** [comment]
That did the trick. Thanks!
