### ISSUE TITLE
ColorScheme: Are colors and icons meant to be configurable?

### ISSUE THREAD

**Issue by Paramethod** [xenial-io/Tasty#77]
https://github.com/xenial-io/Tasty/blob/1c62223328af9ab7d153a62ed84945e0db7a7a71/src/Xenial.Tasty.Core/Reporters/Reporters.ColorScheme.cs#L27-L36

Are these meant to be properties? If they are, I will add a backing field, if they are not I will make them static readonly.

**Comment by Paramethod** [comment]
Seeing the `ColorSchemeLegacy` it seems icons are configurable. So I guess colors are too.

**Comment by biohazard999** [comment]
Yeah they are ment also to be configurable.
You can either use the `ColorSchemeLegacy.Default` property to override them globally.
The preferred way is though setting via the `ColorScheme.Default` cause there is a detection mode for older terminals that don't support UTF8 fonts. 

You also can override the colors directly for reporters, or subclass `ColorScheme` directly.
