### ISSUE TITLE
Remove SuppressMessageAttribute for CLI

### ISSUE THREAD

**Issue by Paramethod** [xenial-io/Tasty#83]
https://github.com/xenial-io/Tasty/blob/45f860e132c770f6632b66938b7b77b93e5fc303/src/Xenial.Tasty.Cli/GlobalSuppressions.cs#L8-L12

Are you maintaining that file manually or is this generated/updated using some utility or designer? Currently these would break if we rename or restructure namespace. Since they are not really 'global' since they have their Target set to a specific member, perhaps we could move them inline and add the standard justifications and checkId to the global suppression file.

**Comment by biohazard999** [comment]
I am not happy with those analyzers in the first way. They come from the VisualStudio team from the JsonRPC. 
There is no way we can avoid them here, cause of convinience overloads.
Yeah those are generated by VS with suppress in supressions file.
If we refactor, those will break anyway cause `WarningsAsErrors` is true.

**Comment by Paramethod** [comment]
Can't we simply disable VSTHRD101 VSTHRD100 as a whole instead?

I've never seen or used the VS Suppress in supressions file tool. I've always added them manually. Good to know it will break because of WarningsAsErrors is true.

Just read an interesting note on https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview

> You should not use in-source suppressions on release builds, to prevent shipping the in-source suppression metadata accidentally. Additionally, because of the processing cost of in-source suppression, the performance of your application can be degraded.

**Comment by biohazard999** [comment]
We shouldn't use the global supressions. Just supress them in CLI
