### ISSUE TITLE
Typo: By me a beer instead of Buy me a beer

### ISSUE THREAD

**Issue by hazard999** [xenial-io/Tasty#95]
https://github.com/xenial-io/Tasty/blob/c3eb125f18ce5949af6fa11f36491a6d70fa342e/docs/input/support/index.cshtml#L68

**Comment by hazard999** [comment]
Although I'm also happy when a beer is by me... 🙈

**Comment by Paramethod** [comment]
captital -> capital

https://github.com/xenial-io/Tasty/blob/c3eb125f18ce5949af6fa11f36491a6d70fa342e/docs/input/support/index.cshtml#L74

**Comment by Paramethod** [comment]
Amount of ingested beers is directly proportional to typos! Perhaps replace beer with chamomile tea? 😉
